Repository 9oormthon-univ/2025_SEASONTHON_TEAM_90_BE, pull requests merged in 2025-09, with the labels that each got.

#25 Refactor: 루틴 도메인 전반적인 구조 개선 및 리팩토링
  api-docs/ROUTINE_API_SPECIFICATION.md
  development-plan.md
  src/main/java/com/groomthon/habiglow/HabiglowApplication.java
  src/main/java/com/groomthon/habiglow/domain/daily/dto/response/RoutineRecordResponse.java
  src/main/java/com/groomthon/habiglow/domain/daily/entity/DailyRoutineEntity.java
  src/main/java/com/groomthon/habiglow/domain/daily/repository/DailyRoutineRepository.java
  src/main/java/com/groomthon/habiglow/domain/daily/service/DailyRoutineService.java
  src/main/java/com/groomthon/habiglow/domain/dashboard/service/WeeklyDashboardService.java
  src/main/java/com/groomthon/habiglow/domain/member/dto/request/UpdateMemberInterestsRequest.java
  src/main/java/com/groomthon/habiglow/domain/member/dto/request/UpdateMemberRequest.java
  src/main/java/com/groomthon/habiglow/domain/member/entity/MemberEntity.java
  src/main/java/com/groomthon/habiglow/domain/member/entity/MemberInterest.java
  src/main/java/com/groomthon/habiglow/domain/member/entity/MemberInterestId.java
  src/main/java/com/groomthon/habiglow/domain/member/service/MemberInterestService.java
  src/main/java/com/groomthon/habiglow/domain/routine/common/RoutineCategory.java
  src/main/java/com/groomthon/habiglow/domain/routine/common/TargetType.java
  src/main/java/com/groomthon/habiglow/domain/routine/controller/RoutineCategoryController.java
  src/main/java/com/groomthon/habiglow/domain/routine/controller/RoutineController.java
  src/main/java/com/groomthon/habiglow/domain/routine/dto/request/CreateRoutineRequest.java
  src/main/java/com/groomthon/habiglow/domain/routine/dto/request/UpdateRoutineRequest.java
  src/main/java/com/groomthon/habiglow/domain/routine/dto/response/GrowthAnalysisResponse.java
  src/main/java/com/groomthon/habiglow/domain/routine/dto/response/GrowthCheckResponse.java
  src/main/java/com/groomthon/habiglow/domain/routine/dto/response/IncreaseTargetResponse.java
  src/main/java/com/groomthon/habiglow/domain/routine/dto/response/ResetGrowthCycleResponse.java
  src/main/java/com/groomthon/habiglow/domain/routine/dto/response/RoutineCategoryResponse.java
  src/main/java/com/groomthon/habiglow/domain/routine/dto/response/RoutineResponse.java
  src/main/java/com/groomthon/habiglow/domain/routine/dto/response/adaptation/AdaptationAction.java
  src/main/java/com/groomthon/habiglow/domain/routine/dto/response/adaptation/AdaptationType.java
  src/main/java/com/groomthon/habiglow/domain/routine/dto/response/adaptation/AdaptiveRoutineCheckResponse.java
  src/main/java/com/groomthon/habiglow/domain/routine/dto/response/adaptation/GrowthReadyRoutineResponse.java
  src/main/java/com/groomthon/habiglow/domain/routine/dto/response/adaptation/ReductionReadyRoutineResponse.java
  src/main/java/com/groomthon/habiglow/domain/routine/dto/response/adaptation/RoutineAdaptationCheckResponse.java
  src/main/java/com/groomthon/habiglow/domain/routine/dto/response/adaptation/RoutineAdaptationResultResponse.java
  src/main/java/com/groomthon/habiglow/domain/routine/entity/GrowthConfiguration.java
  src/main/java/com/groomthon/habiglow/domain/routine/entity/GrowthSettings.java
  src/main/java/com/groomthon/habiglow/domain/routine/entity/RoutineDetails.java
  src/main/java/com/groomthon/habiglow/domain/routine/entity/RoutineEntity.java
  src/main/java/com/groomthon/habiglow/domain/routine/event/GrowthCycleCompletedEvent.java
  src/main/java/com/groomthon/habiglow/domain/routine/event/RoutineCreatedEvent.java
  src/main/java/com/groomthon/habiglow/domain/routine/event/RoutineDeletedEvent.java
  src/main/java/com/groomthon/habiglow/domain/routine/event/RoutineEventHandler.java
  src/main/java/com/groomthon/habiglow/domain/routine/event/RoutineTargetChangedEvent.java
  src/main/java/com/groomthon/habiglow/domain/routine/facade/RoutineManagementFacade.java
  src/main/java/com/groomthon/habiglow/domain/routine/facade/RoutineManagementHelper.java
  src/main/java/com/groomthon/habiglow/domain/routine/facade/RoutineQueryFacade.java
  src/main/java/com/groomthon/habiglow/domain/routine/helper/RoutineHelper.java
  src/main/java/com/groomthon/habiglow/domain/routine/repository/RoutineRepository.java
  src/main/java/com/groomthon/habiglow/domain/routine/service/GrowthAnalysisService.java
  src/main/java/com/groomthon/habiglow/domain/routine/service/GrowthConfigurationService.java
  src/main/java/com/groomthon/habiglow/domain/routine/service/ReductionAnalysisService.java
  src/main/java/com/groomthon/habiglow/domain/routine/service/RoutineDataAccessService.java
  src/main/java/com/groomthon/habiglow/domain/routine/service/RoutineGrowthService.java
  src/main/java/com/groomthon/habiglow/domain/routine/service/RoutineService.java
  src/main/java/com/groomthon/habiglow/domain/routine/service/RoutineValidationService.java
  src/main/java/com/groomthon/habiglow/domain/routine/service/strategy/AdaptationStrategy.java
  src/main/java/com/groomthon/habiglow/domain/routine/service/strategy/GrowthStrategy.java
  src/main/java/com/groomthon/habiglow/domain/routine/service/strategy/ReductionStrategy.java
  src/main/java/com/groomthon/habiglow/global/response/ErrorCode.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: 🔨 Refactor, 🐬규일

#27 feat(routine): 루틴 특화 로직 및 적응형 관리 시스템 구현
  api-docs/DAILY_API_SPECIFICATION.md
  api-docs/ROUTINE_API_SPECIFICATION.md
  development-plan.md
  src/main/java/com/groomthon/habiglow/domain/daily/service/DailyRoutineService.java
  src/main/java/com/groomthon/habiglow/domain/routine/controller/RoutineController.java
  src/main/java/com/groomthon/habiglow/domain/routine/dto/response/RoutineResponse.java
  src/main/java/com/groomthon/habiglow/domain/routine/dto/response/adaptation/GrowthReadyRoutineResponse.java
  src/main/java/com/groomthon/habiglow/domain/routine/dto/response/adaptation/ReductionReadyRoutineResponse.java
  src/main/java/com/groomthon/habiglow/domain/routine/entity/GrowthConfiguration.java
  src/main/java/com/groomthon/habiglow/domain/routine/facade/RoutineManagementFacade.java
  src/main/java/com/groomthon/habiglow/domain/routine/service/GrowthAnalysisService.java
  src/main/java/com/groomthon/habiglow/domain/routine/service/GrowthConfigurationService.java
  src/main/java/com/groomthon/habiglow/domain/routine/service/ReductionAnalysisService.java
  src/main/java/com/groomthon/habiglow/domain/routine/service/RoutineDataAccessService.java
  src/main/java/com/groomthon/habiglow/domain/routine/service/RoutineGrowthService.java
  src/main/java/com/groomthon/habiglow/domain/routine/service/strategy/ReductionStrategy.java
Labels: ✨ Feature, 🐬규일

#35 19 feature/push alarm
  src/main/java/com/groomthon/habiglow/domain/auth/service/DevAuthService.java
  src/main/resources/application-dev.yml
Labels: 🔨 Refactor, 🐇성민

#38 월간 루틴 통계 조회 기능 구현
  api-docs/AUTH_API_SPECIFICATION.md
  api-docs/DAILY_API_SPECIFICATION.md
  api-docs/DASHBOARD_API_SPECIFICATION.md
  api-docs/ROUTINE_API_SPECIFICATION.md
  src/main/java/com/groomthon/habiglow/domain/daily/controller/DailyRecordController.java
  src/main/java/com/groomthon/habiglow/domain/daily/dto/response/MonthlyStatsResponse.java
  src/main/java/com/groomthon/habiglow/domain/daily/event/DailyEventHandler.java
  src/main/java/com/groomthon/habiglow/domain/daily/facade/DailyRecordFacade.java
  src/main/java/com/groomthon/habiglow/domain/daily/repository/DailyRoutineRepository.java
  src/main/java/com/groomthon/habiglow/domain/daily/service/DailyRecordDomainService.java
  src/main/java/com/groomthon/habiglow/domain/daily/service/DailyRecordQueryService.java
  src/main/java/com/groomthon/habiglow/domain/daily/service/DailyRoutineCleanupService.java
  src/main/java/com/groomthon/habiglow/domain/daily/service/DailyRoutineService.java
  src/main/java/com/groomthon/habiglow/global/response/ApiSuccessCode.java
Labels: ✨ Feature, 🐬규일

#41 refactor: 주간 대시보드와 AI 분석의 데이터 일관성 확보 및 유연성 개선
  src/main/java/com/groomthon/habiglow/domain/daily/entity/EmotionType.java
  src/main/java/com/groomthon/habiglow/domain/dashboard/service/WeeklyInsightService.java
  src/main/java/com/groomthon/habiglow/domain/dashboard/util/WeeklyDataCollector.java
Labels: 🔨 Refactor, 🐇성민

#42 refactor: 주간 대시보드와 AI 분석의 데이터 일관성 확보 및 유연성 개선
  api-docs/AUTH_API_SPECIFICATION.md
  api-docs/DAILY_API_SPECIFICATION.md
  api-docs/DASHBOARD_API_SPECIFICATION.md
  api-docs/ROUTINE_API_SPECIFICATION.md
  src/main/java/com/groomthon/habiglow/domain/daily/controller/DailyRecordController.java
  src/main/java/com/groomthon/habiglow/domain/daily/dto/response/MonthlyStatsResponse.java
  src/main/java/com/groomthon/habiglow/domain/daily/entity/EmotionType.java
  src/main/java/com/groomthon/habiglow/domain/daily/event/DailyEventHandler.java
  src/main/java/com/groomthon/habiglow/domain/daily/facade/DailyRecordFacade.java
  src/main/java/com/groomthon/habiglow/domain/daily/repository/DailyRoutineRepository.java
  src/main/java/com/groomthon/habiglow/domain/daily/service/DailyRecordDomainService.java
  src/main/java/com/groomthon/habiglow/domain/daily/service/DailyRecordQueryService.java
  src/main/java/com/groomthon/habiglow/domain/daily/service/DailyRoutineCleanupService.java
  src/main/java/com/groomthon/habiglow/domain/daily/service/DailyRoutineService.java
  src/main/java/com/groomthon/habiglow/domain/dashboard/service/WeeklyInsightService.java
  src/main/java/com/groomthon/habiglow/domain/dashboard/util/WeeklyDataCollector.java
  src/main/java/com/groomthon/habiglow/global/response/ApiSuccessCode.java
Labels: 🔨 Refactor, 🐇성민

#46 refactor: AI 문구 스타일 변화
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 🔨 Refactor, 🐇성민

#48 fix: 대시보드 감정 분포 통계를 실제 EmotionType과 일치하도록 수정
  src/main/java/com/groomthon/habiglow/domain/dashboard/service/WeeklyDashboardService.java
Labels: 🐇성민
